{{- if eq (include "flightctl.isPamIssuerEnabled" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    flightctl.service: flightctl-pam-issuer
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  name: flightctl-pam-issuer
  namespace: {{ .Release.Namespace }}
{{ end }}
